New schemas and docs
PMR-Fansub/subflow-core-go pull request #3
Opened 2023-08-28 17:04 UTC by Ginakira

Changes:
1. add predefined roles when the `role` table is empty.
2. rename some fields.
3. add team, task, task record, workflow, workflow node entities.
4. integrate with swagger.
5. add database ER-diagrams.
6. add documents for API endpoints.

P.S. The branch name is incorrect, plz forgive me.

2023-08-28 17:05 UTC, Ginakira commented
Files under the `pkg` are generated by `ent.go`, please ignore them.

2023-08-29 14:29 UTC, johanvx requested changes

2023-08-29 14:29 UTC, johanvx commented on internal/api/api.go
> +// @Name						Authorization
```suggestion
//	@title		SubFlow API
//	@version	1.0

//	@license.name	GPLv3
//	@license.url	https://www.gnu.org/licenses/gpl-3.0.html

//	@host		localhost:8000
//	@BasePath	/v1

//	@securityDefinitions.apiKey	ApiKeyAuth
//	@In				header
//	@Name				Authorization
```

These lines don't seem to be aligned (Is this because I use 8-character tab?). Maybe it's better to have them aligned.

2023-08-29 16:39 UTC, Ginakira commented on internal/api/api.go
> +// @Name						Authorization
It's a problem TBD, because `swaggo/swag` forced to mixed use space and tab to indent.

2023-08-29 16:42 UTC, Ginakira commented
The type of commit message has been corrected.

2023-08-29 16:49 UTC, johanvx approved these changes
Looks great!

2023-08-29 16:49 UTC, merged